external-links-to-ignore: [ "localhost" ]
files-to-ignore: [ "/vendor/", "test-markdowns" ]
files:
  - path: "./milv/README.md"
    config:
      allow-code-blocks: true
  - path: "./milv/.github/ISSUE_TEMPLATE/security-vulnerability.md"
    config:
      internal-links-to-ignore: [ "{CVSS" ]
      #milv doesn't support that mysterious anchor
      external-links-to-ignore:
        [
            "https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:L/A:N",
        ]
  - path: "./milv/internal-ignore/docs/security/08-04-add-connector.md"
    config:
      white-list-external: [ "https://dex.{CLUSTER_DOMAIN}/callback" ]
      external-links-to-ignore: [ "https://dex.{CLUSTER_DOMAIN}/callback" ]
  - path: "./kyma/docs/kyma/04-10-upgrade.md"
    config:
      white-list-external: [ "https://raw.githubusercontent.com/kyma-project/kyma/{NEW_KYMA_VERSION}/installation/resources/tiller.yaml" ]
      external-links-to-ignore: [ "https://raw.githubusercontent.com/kyma-project/kyma/{NEW_KYMA_VERSION}/installation/resources/tiller.yaml" ]
  - path: "./kyma/docs/README.md"
    config:
      white-list-external: ["kyma-project.io"]
      external-links-to-ignore: ["kyma-project.io"]
  - path: "./kyma/components/helm-broker/docs/proposals/addon-git-support.md"
    config:
      white-list-external: ["https://github.com/kyma-project/addons/blob/master/addons/index.yaml", "https://gitlab.com/kyma-project/addons/blob/master/addons/index.yaml", "https://bitbucket.org/kyma-project/addons/src/master/addons/index.yaml"]
      external-links-to-ignore: ["https://github.com/kyma-project/addons/blob/master/addons/index.yaml", "https://gitlab.com/kyma-project/addons/blob/master/addons/index.yaml", "https://bitbucket.org/kyma-project/addons/src/master/addons/index.yaml"]
  - path: "./kyma/docs/application-connector/012-details-serviceclass-documentation.md"
    config:
      white-list-external: ["https://www.orders.com/v1/orders"]
      external-links-to-ignore: ["https://www.orders.com/v1/orders"]
  - path: "./kyma/docs/helm-broker/05-01-helm-broker.md"
    config:
      white-list-external: ["custom.bundles-repository"]
      external-links-to-ignore: ["custom.bundles-repository"]
  - path: "./kyma/docs/kyma/04-07-aks-xip.io-domain.md"
    config:
      white-list-external: ["https://console.{WILDCARD_DNS}.xip.io"]
      external-links-to-ignore: ["https://console.{WILDCARD_DNS}.xip.io"]
  - path: "./kyma/docs/kyma/04-06-gke-xip.io-domain.md"
    config:
      white-list-external: ["https://console.{WILDCARD_DNS}.xip.io"]
      external-links-to-ignore: ["https://console.{WILDCARD_DNS}.xip.io"]
  - path: "./kyma/docs/helm-broker/08-01-configure-hb.md"
    config:
      white-list-external: ["https://{host}/{path}/{bundle_repo_version"]
      external-links-to-ignore: ["https://{host}/{path}/{bundle_repo_version"]
  - path: "./kyma/docs/application-connector/08-09-revoke-cert.md"
    config:
      white-list-external: ["https://gateway.{CLUSTER_DOMAIN}/v1/applications/certificates/revocations"]
      external-links-to-ignore: ["https://gateway.{CLUSTER_DOMAIN}/v1/applications/certificates/revocations"]
  - path: "./kyma/docs/migration-guides/0.8-0.9.md"
    config:
      white-list-external: ["https://github.com/kyma-project/kyma/releases/tag/0.9.0"]
      external-links-to-ignore: ["https://github.com/kyma-project/kyma/releases/tag/0.9.0"]
  - path: "./kyma/docs/asset-store/05-02-asset-store-metadata-service.md"
    config:
      white-list-external: ["https://{VIRTUALSERVICE_NAME}.{DOMAIN"]
      external-links-to-ignore: ["https://{VIRTUALSERVICE_NAME}.{DOMAIN"]
  - path: "./kyma/docs/asset-store/05-04-asset-upload-service.md"
    config:
      white-list-external: ["https://{VIRTUALSERVICE_NAME}.{DOMAIN"]
      external-links-to-ignore: ["https://{VIRTUALSERVICE_NAME}.{DOMAIN"]
  - path: "./kyma/docs/asset-store/05-01-asset-store.md"